# Usa a imagem base node:14-alpine, que é leve e otimizada para aplicações Node.js
FROM node:14-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos de dependências (package.json e package-lock.json) para o contêiner
COPY package*.json ./

# Instala as dependências da aplicação
RUN npm install

# Copia todo o código da aplicação para o contêiner
COPY . .

# Compila o código para produção
RUN npm run build

# Expõe a porta 3000, onde o React irá servir a aplicação
EXPOSE 3000

# Define o comando padrão para iniciar a aplicação
CMD ["npm", "start"]
