name: Build and Test

# Dispara o workflow em eventos de push e pull request na branch main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  front-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build front-end Docker image
        run: docker build -t front-end-image -f ./front-end/Dockerfile ./front-end

      - name: Run front-end tests
        run: docker run front-end-image npm test

  back-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build back-end Docker image
        run: docker build -t back-end-image -f ./back-end/Dockerfile ./back-end

      - name: Run back-end tests
        run: docker run back-end-image npm test

  database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build database Docker image
        run: docker build -t data-base-image -f ./data-base/Dockerfile ./data-base
