name: Build and Test

# Dispara o workflow em eventos de push e pull request na branch main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  front-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build front-end Docker image
        run: docker build -t frontend-image -f ./frontend/Dockerfile ./frontend

      - name: Run front-end tests
        run: docker run frontend-image npm test

  back-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build back-end Docker image
        run: docker build -t backend-image -f ./backend/Dockerfile ./backend

      - name: Run back-end tests
        run: docker run backend-image npm test

  database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build database Docker image
        run: docker build -t database-image -f ./database/Dockerfile ./database
