name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push front-end Docker image
        run: |
          docker build -t myusername/frontend:latest -f ./frontend/Dockerfile ./frontend
          docker push myusername/frontend:latest

      - name: Build and push back-end Docker image
        run: |
          docker build -t myusername/backend:latest -f ./backend/Dockerfile ./backend
          docker push myusername/backend:latest

      - name: Build and push database Docker image
        run: |
          docker build -t myusername/database:latest -f ./database/Dockerfile ./database
          docker push myusername/database:latest
