name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push front-end Docker image
        run: |
          docker build -t myusername/front-end:latest -f ./front-end/Dockerfile ./front-end
          docker push myusername/front-end:latest

      - name: Build and push back-end Docker image
        run: |
          docker build -t myusername/back-end:latest -f ./back-end/Dockerfile ./back-end
          docker push myusername/back-end:latest

      - name: Build and push database Docker image
        run: |
          docker build -t myusername/data-base:latest -f ./data-base/Dockerfile ./data-base
          docker push myusername/data-base:latest
